### ISSUE TITLE
Why no direct implement this package in vapor-community/HTMLKit?

### ISSUE THREAD

**Issue by diuming** [MatsMoll/htmlkit-vapor-provider#3]
Vapor: 4.0-beta-3.1

Why no direct implement this package in` vapor-community/HTMLKit`?
thanks

**Comment by MatsMoll** [comment]
This was done in an earlier version, but this made it impossible to use `HTMLKit` with `Vapor` 3 and 4. Because of conflicting versions

So it is like this in order to make it possible to use `HTMLKit` with whatever server-framework you want
