### ISSUE TITLE
Documentation, examples

### ISSUE THREAD

**Issue by Magiguigui** [MatsMoll/htmlkit-vapor-provider#4]
The readme ir really poor in general informations... If I understood it's not a real vapor integration but only a factory accessible through `Application.htmlkit` property ? If I succeed to integrate HTMLKit to my project I would provide some example of how to use it in a Vapor context. 

Other : property htmlkit of Request or Application object are inaccessible ?. 

A real implentation accessible through the default request.view.render is a good idea ? (need some config like `app.views.use(HTMLKitRendererProvider.self)`)

**Comment by nonfungibletunji** [comment]
The TIL example, has not been updated to Vapor 4, can we have a example of a example Vapor 4 app?

**Comment by MatsMoll** [comment]
Sorry for the very late replay. But I have added a more detailed README that walks through how to use the provider. I will try to update the TIL repo as well, for a more detailed example.

**Comment by mattesmohr** [comment]
I close the issue. Should be outdated by now.

**Comment by mattesmohr** [comment]
I close the issue. Should be outdated by now.
